/* Generated By:JavaCC: Do not edit this line. CompilerConstants.java */
package at.fhooe.mcm.compiler;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CompilerConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int DIGIT = 5;
  /** RegularExpression Id. */
  int EQUALS = 6;
  /** RegularExpression Id. */
  int LESS = 7;
  /** RegularExpression Id. */
  int GREATER = 8;
  /** RegularExpression Id. */
  int CONTEXT_TEMP = 9;
  /** RegularExpression Id. */
  int CONTEXT_SPEED = 10;
  /** RegularExpression Id. */
  int CONTEXT_DENSITY = 11;
  /** RegularExpression Id. */
  int CONTEXT_TIME = 12;
  /** RegularExpression Id. */
  int CONTEXT_FUEL = 13;
  /** RegularExpression Id. */
  int CONTEXT_POSITION = 14;
  /** RegularExpression Id. */
  int TIME = 15;
  /** RegularExpression Id. */
  int AND = 16;
  /** RegularExpression Id. */
  int OR = 17;
  /** RegularExpression Id. */
  int POINT = 18;
  /** RegularExpression Id. */
  int DISTANCE = 19;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<DIGIT>",
    "\"EQUALS\"",
    "\"LESS\"",
    "\"GREATER\"",
    "\"temp\"",
    "\"speed\"",
    "\"density\"",
    "\"time\"",
    "\"fuel\"",
    "\"position\"",
    "<TIME>",
    "\"AND\"",
    "\"OR\"",
    "\"POINT\"",
    "\"distance\"",
    "\"(\"",
    "\",\"",
    "\")\"",
  };

}
